/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */
public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int transparent=0x7f040000;
    }
    public static final class drawable {
        public static final int accept=0x7f020000;
        public static final int add=0x7f020001;
        public static final int add1=0x7f020002;
        public static final int ant=0x7f020003;
        public static final int ant1=0x7f020004;
        public static final int bg_azul=0x7f020005;
        public static final int bg_button=0x7f020006;
        public static final int busca=0x7f020007;
        public static final int busca1=0x7f020008;
        public static final int cancel=0x7f020009;
        public static final int chart=0x7f02000a;
        public static final int chart1=0x7f02000b;
        public static final int conection=0x7f02000c;
        public static final int conection1=0x7f02000d;
        public static final int delete=0x7f02000e;
        public static final int delete1=0x7f02000f;
        public static final int exit=0x7f020010;
        public static final int financeiro=0x7f020011;
        public static final int financeiro1=0x7f020012;
        public static final int gradient=0x7f020013;
        public static final int ic_drag_normal=0x7f020014;
        public static final int ic_drag_pressed=0x7f020015;
        public static final int ic_launcher=0x7f020016;
        public static final int ic_launcher_1=0x7f020017;
        public static final int logo_unica=0x7f020018;
        public static final int order=0x7f020019;
        public static final int order1=0x7f02001a;
        public static final int prox=0x7f02001b;
        public static final int prox1=0x7f02001c;
        public static final int tab_bg_selected=0x7f02001d;
        public static final int tab_bg_selector=0x7f02001e;
        public static final int tab_bg_unselected=0x7f02001f;
        public static final int tab_divider=0x7f020020;
        public static final int tab_text_selector=0x7f020021;
    }
    public static final class id {
        public static final int LinearLayout=0x7f08001d;
        public static final int TableRow01=0x7f08001e;
        public static final int TableRow02=0x7f080038;
        public static final int TableRow03=0x7f08002e;
        public static final int TableRow04=0x7f080030;
        public static final int TableRow2=0x7f08003f;
        public static final int TableRow3=0x7f080041;
        public static final int TextView01=0x7f080009;
        public static final int TextView02=0x7f080007;
        public static final int TextView03=0x7f080005;
        public static final int TextView04=0x7f080037;
        public static final int TextView06=0x7f08002f;
        public static final int TvDados=0x7f08001c;
        public static final int btAvancar=0x7f080011;
        public static final int btBuscaCli=0x7f080010;
        public static final int btConectar=0x7f080019;
        public static final int btConexao=0x7f08000a;
        public static final int btEntrar=0x7f080042;
        public static final int btFinalizar=0x7f08002c;
        public static final int btFinanceiro=0x7f080004;
        public static final int btOpcoes=0x7f080049;
        public static final int btPedidos=0x7f080002;
        public static final int btPesquisaProd=0x7f080045;
        public static final int btRelatorios=0x7f080008;
        public static final int btRetornar=0x7f08000c;
        public static final int btSair=0x7f080006;
        public static final int btSelecionar=0x7f080046;
        public static final int btTest=0x7f08001a;
        public static final int btVoltar=0x7f08001b;
        public static final int btnCanc=0x7f08003b;
        public static final int btnConcluir=0x7f08003c;
        public static final int btnExc=0x7f080034;
        public static final int btnGravar=0x7f080035;
        public static final int config=0x7f08004c;
        public static final int datagrid=0x7f080036;
        public static final int datagrid_clientes=0x7f080013;
        public static final int datagrid_produtos=0x7f080047;
        public static final int datagrid_relvendas=0x7f080048;
        public static final int dgCar=0x7f08002d;
        public static final int imageView1=0x7f080000;
        public static final int lbCliente=0x7f080020;
        public static final int lbItens=0x7f080022;
        public static final int lbOperador=0x7f08003e;
        public static final int lbPedido=0x7f08001f;
        public static final int lbRetorno=0x7f080017;
        public static final int lbSaud=0x7f08003d;
        public static final int lbTotal=0x7f080024;
        public static final int limpar=0x7f08004d;
        public static final int linearLayout1=0x7f080001;
        public static final int menu_settings=0x7f08004e;
        public static final int progressBar1=0x7f080018;
        public static final int relativeLayout2=0x7f080025;
        public static final int relativeLayout3=0x7f080028;
        public static final int tableRow1=0x7f08000e;
        public static final int tableRow2=0x7f080012;
        public static final int tableRow3=0x7f080014;
        public static final int tableRow4=0x7f080016;
        public static final int tableRow5=0x7f08000d;
        public static final int tabsLayout=0x7f08004a;
        public static final int tabsText=0x7f08004b;
        public static final int tbBusca=0x7f080031;
        public static final int tbBuscaCli=0x7f08000f;
        public static final int tbItensPed=0x7f080039;
        public static final int tbObs=0x7f080027;
        public static final int tbParcelas=0x7f08002a;
        public static final int tbPesqFabricante=0x7f080044;
        public static final int tbPesqProd=0x7f080043;
        public static final int tbPreco=0x7f080033;
        public static final int tbQtd=0x7f080032;
        public static final int tbSenha=0x7f080040;
        public static final int tbTotalPed=0x7f08003a;
        public static final int textView1=0x7f080003;
        public static final int textView2=0x7f080015;
        public static final int textView3=0x7f08000b;
        public static final int textView4=0x7f080021;
        public static final int textView5=0x7f080023;
        public static final int textView6=0x7f080026;
        public static final int textView7=0x7f080029;
        public static final int textView8=0x7f08002b;
    }
    public static final class layout {
        public static final int activity_main=0x7f030000;
        public static final int cliente=0x7f030001;
        public static final int conexao=0x7f030002;
        public static final int finalped=0x7f030003;
        public static final int financeiro=0x7f030004;
        public static final int financeiro_cliente=0x7f030005;
        public static final int itvendas=0x7f030006;
        public static final int login=0x7f030007;
        public static final int pesquisa_prod=0x7f030008;
        public static final int prefscreen=0x7f030009;
        public static final int relatorio_vendas_ana=0x7f03000a;
        public static final int relatorio_vendas_sin=0x7f03000b;
        public static final int relatorios_tab=0x7f03000c;
        public static final int tabs_bg=0x7f03000d;
    }
    public static final class menu {
        public static final int activity_main_menu=0x7f070000;
        public static final int activity_preferencias=0x7f070001;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
        public static final int hello_world=0x7f050001;
        public static final int menu_settings=0x7f050002;
        public static final int title_activity_preferencias=0x7f050003;
    }
    public static final class style {
        /**  Global Theme Styles 

        Base application theme, dependent on API level. This theme is replaced
        by AppBaseTheme from res/values-vXX/styles.xml on newer devices.
    

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        
         */
        public static final int AppBaseTheme=0x7f060000;
        /**  Application theme. 
 All customizations that are NOT specific to a particular API-level can go here. 
         */
        public static final int AppTheme=0x7f060001;
    }
}
